name: CI-CD Infrastructure and Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Configure
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply
        id: tf
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
          # Export IPs as step outputs
          echo "NGINX_IP=$(terraform output -raw nginx_public_ip)" >> $GITHUB_OUTPUT
          echo "JAVA_IP=$(terraform output -raw java_public_ip)" >> $GITHUB_OUTPUT

      - name: Prepare Ansible Inventory
        run: |
          # Dynamically create the inventory file using the IPs from Terraform
          echo "[web]" > inventories/dev.ini
          echo "${{ steps.tf.outputs.NGINX_IP }} ansible_user=ec2-user" >> inventories/dev.ini
          echo "[app]" >> inventories/dev.ini
          echo "${{ steps.tf.outputs.JAVA_IP }} ansible_user=ec2-user" >> inventories/dev.ini

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem

      - name: Run Ansible Playbook
        run: |
          # Disable host key checking and run the playbook
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventories/dev.ini playbook.yml \
            --private-key /tmp/key.pem